package wakeword

import (
	"encoding/binary"
	"math"
	"os"
	"testing"
)

// The fixture is a golden capture of openwakeword's own streaming behaviour,
// generated by feeding a real 2.8s device recording through
// openwakeword.utils.AudioFeatures and recording, per 80ms chunk:
//
//   - the length of the audio slice handed to the melspectrogram model, and
//     that model's raw output (which the mock replays, so this test needs no
//     ONNX Runtime);
//   - an FNV-1a hash of the exact 76x32 window handed to the embedding model;
//   - the embedding the model returned (also replayed);
//   - an FNV-1a hash of the exact 16x96 tensor handed to the classifier, and
//     the resulting score.
//
// Replaying the model outputs and asserting on the model INPUTS is what makes
// this a test of the buffering rather than of the models: every ring
// boundary, window offset and transform has to be right or the hashes
// diverge. A test that only replayed inputs and compared final scores would
// pass with the windows subtly misaligned.
type record struct {
	melInLen int
	melOut   []float32
	winFNV   uint64
	emb      []float32
	featFNV  uint64
	score    float32
}

func loadFixture(t *testing.T) []record {
	t.Helper()
	raw, err := os.ReadFile("testdata/stream_fixture.bin")
	if err != nil {
		t.Fatalf("read fixture: %v", err)
	}
	if string(raw[:8]) != "OWWFIX01" {
		t.Fatalf("bad fixture magic %q", raw[:8])
	}
	p := 8
	u32 := func() int { v := binary.LittleEndian.Uint32(raw[p:]); p += 4; return int(v) }
	u64 := func() uint64 { v := binary.LittleEndian.Uint64(raw[p:]); p += 8; return v }
	f32n := func(n int) []float32 {
		out := make([]float32, n)
		for i := range out {
			out[i] = math.Float32frombits(binary.LittleEndian.Uint32(raw[p:]))
			p += 4
		}
		return out
	}
	n := u32()
	recs := make([]record, n)
	for i := range recs {
		recs[i].melInLen = u32()
		frames := u32()
		recs[i].melOut = f32n(frames * MelBins)
		recs[i].winFNV = u64()
		recs[i].emb = f32n(FeatDim)
		recs[i].featFNV = u64()
		recs[i].score = f32n(1)[0]
	}
	if p != len(raw) {
		t.Fatalf("fixture not fully consumed: %d of %d bytes", p, len(raw))
	}
	return recs
}

func fnv1a(vals []float32) uint64 {
	const (
		offset = uint64(14695981039346656037)
		prime  = uint64(1099511628211)
	)
	h := offset
	var b [4]byte
	for _, v := range vals {
		binary.LittleEndian.PutUint32(b[:], math.Float32bits(v))
		for _, c := range b {
			h = (h ^ uint64(c)) * prime
		}
	}
	return h
}

// replayInferer returns the fixture's recorded model outputs and asserts that
// the inputs it is handed match what Python fed at the same point.
type replayInferer struct {
	t    *testing.T
	recs []record
	i    int // index of the chunk currently being processed

	gotMelLen  []int
	gotWinFNV  []uint64
	gotFeatFNV []uint64
}

func (r *replayInferer) Melspec(samples []float32) ([]float32, int, error) {
	r.gotMelLen = append(r.gotMelLen, len(samples))
	rec := r.recs[r.i]
	return rec.melOut, len(rec.melOut) / MelBins, nil
}

func (r *replayInferer) Embed(window []float32) ([]float32, error) {
	r.gotWinFNV = append(r.gotWinFNV, fnv1a(window))
	return r.recs[r.i].emb, nil
}

func (r *replayInferer) Classify(feats []float32) (float32, error) {
	r.gotFeatFNV = append(r.gotFeatFNV, fnv1a(feats))
	return r.recs[r.i].score, nil
}

// TestStreamMatchesPython is the whole point of this package's test suite:
// the buffering must reproduce openwakeword's, tensor for tensor.
func TestStreamMatchesPython(t *testing.T) {
	recs := loadFixture(t)
	if len(recs) < FeatWindow+4 {
		t.Fatalf("fixture too short to exercise the feature ring: %d chunks", len(recs))
	}
	inf := &replayInferer{t: t, recs: recs}
	d := New(inf)

	audio := make([]int16, ChunkSamples) // contents irrelevant; models are replayed
	for i := range recs {
		inf.i = i
		n, err := d.Push(audio)
		if err != nil {
			t.Fatalf("chunk %d: Push: %v", i, err)
		}
		if n != 1 {
			t.Fatalf("chunk %d: produced %d embeddings, want exactly 1", i, n)
		}
		// Upstream seeds its feature ring with 41 embeddings of random audio,
		// so its first FeatWindow scores are computed partly against noise
		// and cannot be reproduced by an implementation that starts clean.
		// From chunk FeatWindow onward the window is entirely real audio and
		// must match exactly.
		if i < FeatWindow {
			continue
		}
		if !d.Ready() {
			t.Fatalf("chunk %d: not Ready with %d embeddings buffered", i, len(d.feat)/FeatDim)
		}
		if _, err := d.Score(); err != nil {
			t.Fatalf("chunk %d: Score: %v", i, err)
		}
	}

	// Melspectrogram input length: 1280 on the very first chunk (the ring
	// holds nothing else yet) and 1760 thereafter. Getting this wrong yields
	// 5 mel frames per chunk instead of 8 and silently desynchronises the
	// embedding window from the audio.
	for i, got := range inf.gotMelLen {
		if want := recs[i].melInLen; got != want {
			t.Errorf("chunk %d: melspec input %d samples, want %d", i, got, want)
		}
	}
	// The exact 76x32 window fed to the embedding model, from chunk 0 —
	// reproducible because the mel ring's 1.0 pre-fill is deterministic.
	for i, got := range inf.gotWinFNV {
		if want := recs[i].winFNV; got != want {
			t.Errorf("chunk %d: embedding window hash %016x, want %016x", i, got, want)
		}
	}
	// The exact 16x96 classifier input, once the ring is all real audio.
	for j, got := range inf.gotFeatFNV {
		i := j + FeatWindow
		if want := recs[i].featFNV; got != want {
			t.Errorf("chunk %d: classifier input hash %016x, want %016x", i, got, want)
		}
	}
}

// TestNotReadyBeforeSixteenEmbeddings pins the deliberate divergence from
// upstream: no score at all until the window is real, rather than a score
// derived from random warm-up data.
func TestNotReadyBeforeSixteenEmbeddings(t *testing.T) {
	recs := loadFixture(t)
	inf := &replayInferer{t: t, recs: recs}
	d := New(inf)
	audio := make([]int16, ChunkSamples)
	for i := 0; i < FeatWindow-1; i++ {
		inf.i = i
		if _, err := d.Push(audio); err != nil {
			t.Fatal(err)
		}
		if d.Ready() {
			t.Fatalf("Ready after only %d embeddings", i+1)
		}
		if _, err := d.Score(); err != ErrNotReady {
			t.Fatalf("Score returned %v, want ErrNotReady", err)
		}
	}
	inf.i = FeatWindow - 1
	if _, err := d.Push(audio); err != nil {
		t.Fatal(err)
	}
	if !d.Ready() {
		t.Fatal("not Ready after 16 embeddings")
	}
}

// sizedInferer models the melspectrogram model's actual output size —
// ceil(samples/160 - 3) frames — instead of replaying a fixed recording.
// The structural tests below push chunk sizes the fixture never captured, so
// a replaying mock would hand back the wrong number of mel frames and fail
// them for the mock's reasons rather than the code's.
type sizedInferer struct{ embeds int }

func (s *sizedInferer) Melspec(samples []float32) ([]float32, int, error) {
	frames := int(math.Ceil(float64(len(samples))/160.0 - 3.0))
	if frames < 0 {
		frames = 0
	}
	return make([]float32, frames*MelBins), frames, nil
}
func (s *sizedInferer) Embed(window []float32) ([]float32, error) {
	s.embeds++
	return make([]float32, FeatDim), nil
}
func (s *sizedInferer) Classify(feats []float32) (float32, error) { return 0, nil }

// TestSizedInfererMatchesFixtureFrameCounts keeps the model above honest: the
// frame counts it synthesises must equal what the real model produced in the
// fixture, or the structural tests are asserting against a fiction.
func TestSizedInfererMatchesFixtureFrameCounts(t *testing.T) {
	recs := loadFixture(t)
	var s sizedInferer
	for i, rec := range recs {
		_, frames, _ := s.Melspec(make([]float32, rec.melInLen))
		if want := len(rec.melOut) / MelBins; frames != want {
			t.Fatalf("chunk %d: %d samples -> %d frames, real model gave %d",
				i, rec.melInLen, frames, want)
		}
	}
}

// TestPartialChunksAreHeld covers the remainder path: audio arriving in sizes
// that are not multiples of 1280 must accumulate, not be dropped or padded.
// The device's mic path delivers 80ms frames today, so this guards a
// behaviour nothing currently exercises — which is exactly when it breaks.
func TestPartialChunksAreHeld(t *testing.T) {
	d := New(&sizedInferer{})

	// 1280 samples delivered as 500 + 500 + 280 must produce exactly one
	// embedding, and only on the final call.
	for _, n := range []int{500, 500} {
		got, err := d.Push(make([]int16, n))
		if err != nil {
			t.Fatal(err)
		}
		if got != 0 {
			t.Fatalf("partial push of %d produced %d embeddings, want 0", n, got)
		}
	}
	got, err := d.Push(make([]int16, 280))
	if err != nil {
		t.Fatal(err)
	}
	if got != 1 {
		t.Fatalf("completing chunk produced %d embeddings, want 1", got)
	}
}

// TestOversizeChunkProducesMultipleEmbeddings covers the other half of the
// remainder logic: the device reads 160ms ALSA batches, so a 2560-sample
// push is the realistic case and must yield two embeddings, not one.
func TestOversizeChunkProducesMultipleEmbeddings(t *testing.T) {
	d := New(&sizedInferer{})
	got, err := d.Push(make([]int16, 2*ChunkSamples+37))
	if err != nil {
		t.Fatal(err)
	}
	if got != 2 {
		t.Fatalf("2.03 chunks produced %d embeddings, want 2", got)
	}
	// The 37-sample tail must be retained, so 1280-37 more samples complete
	// the next chunk.
	got, err = d.Push(make([]int16, ChunkSamples-37))
	if err != nil {
		t.Fatal(err)
	}
	if got != 1 {
		t.Fatalf("completing the held tail produced %d embeddings, want 1", got)
	}
}

// TestResetClearsState guards against audio from before a mic restart
// contributing to a score after it.
func TestResetClearsState(t *testing.T) {
	recs := loadFixture(t)
	inf := &replayInferer{t: t, recs: recs}
	d := New(inf)
	audio := make([]int16, ChunkSamples)
	for i := 0; i < FeatWindow; i++ {
		inf.i = i
		if _, err := d.Push(audio); err != nil {
			t.Fatal(err)
		}
	}
	if !d.Ready() {
		t.Fatal("expected Ready before Reset")
	}
	d.Reset()
	if d.Ready() {
		t.Fatal("Ready after Reset")
	}
	if _, err := d.Score(); err != ErrNotReady {
		t.Fatalf("Score after Reset returned %v, want ErrNotReady", err)
	}
	// And the mel ring must be back to its 1.0 pre-fill, not empty, or the
	// first window after a restart differs from the first window at boot.
	if len(d.mel) != MelWindow*MelBins {
		t.Fatalf("mel ring is %d values after Reset, want %d", len(d.mel), MelWindow*MelBins)
	}
	for i, v := range d.mel {
		if v != 1.0 {
			t.Fatalf("mel ring index %d is %v after Reset, want 1.0", i, v)
		}
	}
}
